//! Operation-level SDK capability catalog.

use serde::Serialize;

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum CapabilityTier {
    Public,
    Authenticated,
    Wallet,
    Execution,
    Bridge,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum CapabilityOperation {
    List,
    Get,
    Search,
    Read,
    Stream,
    Derive,
    Sign,
    Create,
    Submit,
    Cancel,
    Update,
    Simulate,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum CapabilityTransport {
    Local,
    Https,
    Wss,
    Rpc,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
pub enum AuthRequirement {
    #[serde(rename = "none")]
    None,
    #[serde(rename = "l1")]
    L1,
    #[serde(rename = "l2")]
    L2,
    #[serde(rename = "siwe")]
    Siwe,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum SigningRequirement {
    None,
    Wallet,
}

#[derive(Clone, Copy, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub enum CapabilityStatus {
    Implemented,
    DtoOnly,
    Unsupported,
    Planned,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize)]
#[serde(rename_all = "camelCase")]
pub struct Capability {
    pub id: &'static str,
    pub tier: CapabilityTier,
    pub service: &'static str,
    pub operation: CapabilityOperation,
    pub transport: CapabilityTransport,
    pub auth: &'static [AuthRequirement],
    pub signing: SigningRequirement,
    pub mutates: bool,
    pub cli_command: Option<&'static [&'static str]>,
    pub extension: bool,
    pub summary: &'static str,
    pub status: CapabilityStatus,
}

pub struct CapabilityCatalog;

impl CapabilityCatalog {
    pub fn all() -> &'static [Capability] {
        CAPABILITIES
    }

    pub fn by_id(id: &str) -> Option<&'static Capability> {
        CAPABILITIES
            .binary_search_by(|cap| cap.id.cmp(id))
            .ok()
            .map(|index| &CAPABILITIES[index])
    }
}

const NONE: &[AuthRequirement] = &[AuthRequirement::None];
const L1: &[AuthRequirement] = &[AuthRequirement::L1];
const L2: &[AuthRequirement] = &[AuthRequirement::L2];
const SIWE: &[AuthRequirement] = &[AuthRequirement::Siwe];

const CAPABILITIES: &[Capability] = &[
    Capability {
        id: "approve.check",
        tier: CapabilityTier::Execution,
        service: "approve",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Rpc,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["approve", "check"]),
        extension: false,
        summary: "Approve check.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "approve.set",
        tier: CapabilityTier::Execution,
        service: "approve",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Rpc,
        auth: NONE,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["approve", "set"]),
        extension: false,
        summary: "Approve set.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "auth.l1.headers.create",
        tier: CapabilityTier::Authenticated,
        service: "auth",
        operation: CapabilityOperation::Create,
        transport: CapabilityTransport::Local,
        auth: L1,
        signing: SigningRequirement::Wallet,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Auth l1 headers create.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "auth.l2.headers.create",
        tier: CapabilityTier::Authenticated,
        service: "auth",
        operation: CapabilityOperation::Create,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Auth l2 headers create.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "auth.siwe.session.create",
        tier: CapabilityTier::Authenticated,
        service: "auth",
        operation: CapabilityOperation::Create,
        transport: CapabilityTransport::Local,
        auth: SIWE,
        signing: SigningRequirement::Wallet,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Auth siwe session create.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "bridge.assets.read",
        tier: CapabilityTier::Bridge,
        service: "bridge",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["bridge", "supported-assets"]),
        extension: false,
        summary: "Bridge assets read.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "bridge.depositAddress.create",
        tier: CapabilityTier::Bridge,
        service: "bridge",
        operation: CapabilityOperation::Create,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["bridge", "deposit"]),
        extension: false,
        summary: "Bridge deposit address create.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "bridge.quote.read",
        tier: CapabilityTier::Bridge,
        service: "bridge",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Bridge quote read.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "bridge.status.read",
        tier: CapabilityTier::Bridge,
        service: "bridge",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["bridge", "status"]),
        extension: false,
        summary: "Bridge status read.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "bridge.withdraw.simulate",
        tier: CapabilityTier::Bridge,
        service: "bridge",
        operation: CapabilityOperation::Simulate,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Bridge withdraw simulate.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "bridge.withdraw.submit",
        tier: CapabilityTier::Bridge,
        service: "bridge",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: None,
        extension: true,
        summary: "Bridge withdraw submit.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "chainlink.price.read",
        tier: CapabilityTier::Public,
        service: "chainlink",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Rpc,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Chainlink price read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.accountStatus.read",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "account-status"]),
        extension: false,
        summary: "Clob account status read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.apiKey.createOrDerive",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Create,
        transport: CapabilityTransport::Https,
        auth: L1,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["clob", "create-api-key"]),
        extension: false,
        summary: "Clob api key create or derive.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.apiKey.delete",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Update,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: true,
        cli_command: Some(&["clob", "delete-api-key"]),
        extension: false,
        summary: "Clob api key delete.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.apiKeys.list",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "api-keys"]),
        extension: false,
        summary: "Clob api keys list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.balance.read",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "balance"]),
        extension: false,
        summary: "Clob balance read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.balance.update",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Update,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: true,
        cli_command: Some(&["clob", "update-balance"]),
        extension: false,
        summary: "Clob balance update.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.book.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "book"]),
        extension: false,
        summary: "Clob book read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.books.batchRead",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "books"]),
        extension: false,
        summary: "Clob books batch read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.builderFeeKey.create",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Create,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Clob builder fee key create.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.builderFeeKey.revoke",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Update,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Clob builder fee key revoke.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.builderFeeKeys.list",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Clob builder fee keys list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.builderTrades.list",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Clob builder trades list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.currentRewards.list",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "current-rewards"]),
        extension: false,
        summary: "Clob current rewards list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.earnings.read",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "earnings"]),
        extension: false,
        summary: "Clob earnings read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.earningsByMarket.list",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "earnings-markets"]),
        extension: false,
        summary: "Clob earnings by market list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.feeRate.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "fee-rate"]),
        extension: false,
        summary: "Clob fee rate read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.geoblock.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "geoblock"]),
        extension: false,
        summary: "Clob geoblock read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.health.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "ok"]),
        extension: false,
        summary: "Clob health read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.lastTrade.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "last-trade"]),
        extension: false,
        summary: "Clob last trade read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.lastTrades.batchRead",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "last-trades"]),
        extension: false,
        summary: "Clob last trades batch read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.market.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "market"]),
        extension: false,
        summary: "Clob market read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.marketOutcome.resolve",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Clob market outcome resolve.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.marketReward.read",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "market-reward"]),
        extension: false,
        summary: "Clob market reward read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.markets.list",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "markets"]),
        extension: false,
        summary: "Clob markets list.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.midpoint.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "midpoint"]),
        extension: false,
        summary: "Clob midpoint read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.midpoints.batchRead",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "midpoints"]),
        extension: false,
        summary: "Clob midpoints batch read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.negRisk.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "neg-risk"]),
        extension: false,
        summary: "Clob neg risk read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.notifications.delete",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Update,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: true,
        cli_command: Some(&["clob", "delete-notifications"]),
        extension: false,
        summary: "Clob notifications delete.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.notifications.list",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "notifications"]),
        extension: false,
        summary: "Clob notifications list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.order.cancel",
        tier: CapabilityTier::Execution,
        service: "clob",
        operation: CapabilityOperation::Cancel,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["clob", "cancel"]),
        extension: false,
        summary: "Clob order cancel.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "clob.order.read",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "order"]),
        extension: false,
        summary: "Clob order read.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "clob.orderScoring.read",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "order-scoring"]),
        extension: false,
        summary: "Clob order scoring read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.orders.all.cancel",
        tier: CapabilityTier::Execution,
        service: "clob",
        operation: CapabilityOperation::Cancel,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["clob", "cancel-all"]),
        extension: false,
        summary: "Clob orders all cancel.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "clob.orders.batch.cancel",
        tier: CapabilityTier::Execution,
        service: "clob",
        operation: CapabilityOperation::Cancel,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["clob", "cancel-orders"]),
        extension: false,
        summary: "Clob orders batch cancel.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "clob.orders.batch.submit",
        tier: CapabilityTier::Execution,
        service: "clob",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["clob", "post-orders"]),
        extension: false,
        summary: "Clob orders batch submit.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "clob.orders.limit.submit",
        tier: CapabilityTier::Execution,
        service: "clob",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["clob", "create-order"]),
        extension: false,
        summary: "Clob orders limit submit.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "clob.orders.list",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "orders"]),
        extension: false,
        summary: "Clob orders list.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "clob.orders.market.cancel",
        tier: CapabilityTier::Execution,
        service: "clob",
        operation: CapabilityOperation::Cancel,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["clob", "cancel-market"]),
        extension: false,
        summary: "Clob orders market cancel.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "clob.orders.market.submit",
        tier: CapabilityTier::Execution,
        service: "clob",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["clob", "market-order"]),
        extension: false,
        summary: "Clob orders market submit.",
        status: CapabilityStatus::DtoOnly,
    },
    Capability {
        id: "clob.ordersScoring.read",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "orders-scoring"]),
        extension: false,
        summary: "Clob orders scoring read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.price.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "price"]),
        extension: false,
        summary: "Clob price read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.priceHistory.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "price-history"]),
        extension: false,
        summary: "Clob price history read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.prices.batchRead",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "batch-prices"]),
        extension: false,
        summary: "Clob prices batch read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.publicTrades.list",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Clob public trades list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.rewardPercentages.read",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "reward-percentages"]),
        extension: false,
        summary: "Clob reward percentages read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.rewards.list",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "rewards"]),
        extension: false,
        summary: "Clob rewards list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.samplingMarkets.list",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "sampling-markets"]),
        extension: false,
        summary: "Clob sampling markets list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.simplifiedMarkets.list",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "simplified-markets"]),
        extension: false,
        summary: "Clob simplified markets list.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.simplifiedSamplingMarkets.list",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "sampling-simp-markets"]),
        extension: false,
        summary: "Clob simplified sampling markets list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.spread.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "spread"]),
        extension: false,
        summary: "Clob spread read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.spreads.batchRead",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "spreads"]),
        extension: false,
        summary: "Clob spreads batch read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "clob.tickSize.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "tick-size"]),
        extension: false,
        summary: "Clob tick size read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.time.read",
        tier: CapabilityTier::Public,
        service: "clob",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "time"]),
        extension: false,
        summary: "Clob time read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "clob.trades.list",
        tier: CapabilityTier::Authenticated,
        service: "clob",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["clob", "trades"]),
        extension: false,
        summary: "Clob trades list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "comments.byUser.list",
        tier: CapabilityTier::Public,
        service: "comments",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["comments", "by-user"]),
        extension: false,
        summary: "Comments by user list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "comments.get",
        tier: CapabilityTier::Public,
        service: "comments",
        operation: CapabilityOperation::Get,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["comments", "get"]),
        extension: false,
        summary: "Comments get.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "comments.list",
        tier: CapabilityTier::Public,
        service: "comments",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["comments", "list"]),
        extension: false,
        summary: "Comments list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "ctf.collectionId.derive",
        tier: CapabilityTier::Execution,
        service: "ctf",
        operation: CapabilityOperation::Derive,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["ctf", "collection-id"]),
        extension: false,
        summary: "Ctf collection id derive.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "ctf.conditionId.derive",
        tier: CapabilityTier::Execution,
        service: "ctf",
        operation: CapabilityOperation::Derive,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["ctf", "condition-id"]),
        extension: false,
        summary: "Ctf condition id derive.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "ctf.merge",
        tier: CapabilityTier::Execution,
        service: "ctf",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Rpc,
        auth: NONE,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["ctf", "merge"]),
        extension: false,
        summary: "Ctf merge.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "ctf.positionId.derive",
        tier: CapabilityTier::Execution,
        service: "ctf",
        operation: CapabilityOperation::Derive,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["ctf", "position-id"]),
        extension: false,
        summary: "Ctf position id derive.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "ctf.redeem",
        tier: CapabilityTier::Execution,
        service: "ctf",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Rpc,
        auth: NONE,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["ctf", "redeem"]),
        extension: false,
        summary: "Ctf redeem.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "ctf.redeemNegRisk",
        tier: CapabilityTier::Execution,
        service: "ctf",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Rpc,
        auth: NONE,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["ctf", "redeem-neg-risk"]),
        extension: false,
        summary: "Ctf redeem neg risk.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "ctf.split",
        tier: CapabilityTier::Execution,
        service: "ctf",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Rpc,
        auth: NONE,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: Some(&["ctf", "split"]),
        extension: false,
        summary: "Ctf split.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "data.activity.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "activity"]),
        extension: false,
        summary: "Data activity read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "data.builderLeaderboard.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "builder-leaderboard"]),
        extension: false,
        summary: "Data builder leaderboard read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "data.builderVolume.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "builder-volume"]),
        extension: false,
        summary: "Data builder volume read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "data.closedPositions.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "closed-positions"]),
        extension: false,
        summary: "Data closed positions read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "data.holders.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "holders"]),
        extension: false,
        summary: "Data holders read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "data.leaderboard.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "leaderboard"]),
        extension: false,
        summary: "Data leaderboard read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "data.marketTrades.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Data market trades read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "data.marketsTraded.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "traded"]),
        extension: false,
        summary: "Data markets traded read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "data.openInterest.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "open-interest"]),
        extension: false,
        summary: "Data open interest read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "data.positions.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "positions"]),
        extension: false,
        summary: "Data positions read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "data.smartWalletTrades.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Data smart wallet trades read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "data.trades.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "trades"]),
        extension: false,
        summary: "Data trades read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "data.value.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "value"]),
        extension: false,
        summary: "Data value read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "data.volume.read",
        tier: CapabilityTier::Public,
        service: "data",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["data", "volume"]),
        extension: false,
        summary: "Data volume read.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "events.get",
        tier: CapabilityTier::Public,
        service: "events",
        operation: CapabilityOperation::Get,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["events", "get"]),
        extension: false,
        summary: "Events get.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "events.list",
        tier: CapabilityTier::Public,
        service: "events",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["events", "list"]),
        extension: false,
        summary: "Events list.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "events.tags.list",
        tier: CapabilityTier::Public,
        service: "events",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["events", "tags"]),
        extension: false,
        summary: "Events tags list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "intel.marketFlow.read",
        tier: CapabilityTier::Public,
        service: "intel",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Intel market flow read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "intel.wallet.alerts",
        tier: CapabilityTier::Public,
        service: "intel",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Intel wallet alerts.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "intel.wallet.dossier",
        tier: CapabilityTier::Public,
        service: "intel",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Intel wallet dossier.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "intel.wallet.score",
        tier: CapabilityTier::Public,
        service: "intel",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Intel wallet score.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "market.discover",
        tier: CapabilityTier::Public,
        service: "market",
        operation: CapabilityOperation::Search,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Market discover.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "market.resolve",
        tier: CapabilityTier::Public,
        service: "market",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Market resolve.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "marketDetail.bundle.read",
        tier: CapabilityTier::Public,
        service: "marketDetail",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Market detail bundle read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "markets.get",
        tier: CapabilityTier::Public,
        service: "markets",
        operation: CapabilityOperation::Get,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["markets", "get"]),
        extension: false,
        summary: "Markets get.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "markets.list",
        tier: CapabilityTier::Public,
        service: "markets",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["markets", "list"]),
        extension: false,
        summary: "Markets list.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "markets.search",
        tier: CapabilityTier::Public,
        service: "markets",
        operation: CapabilityOperation::Search,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["markets", "search"]),
        extension: false,
        summary: "Markets search.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "markets.tags.list",
        tier: CapabilityTier::Public,
        service: "markets",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["markets", "tags"]),
        extension: false,
        summary: "Markets tags list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "opportunities.scan",
        tier: CapabilityTier::Public,
        service: "opportunities",
        operation: CapabilityOperation::Search,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Opportunities scan.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "orderfills.read",
        tier: CapabilityTier::Public,
        service: "orderfills",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Rpc,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Orderfills read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "paper.order.cancel",
        tier: CapabilityTier::Public,
        service: "paper",
        operation: CapabilityOperation::Cancel,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Paper order cancel.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "paper.order.submit",
        tier: CapabilityTier::Public,
        service: "paper",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Paper order submit.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "profiles.get",
        tier: CapabilityTier::Public,
        service: "profiles",
        operation: CapabilityOperation::Get,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["profiles", "get"]),
        extension: false,
        summary: "Profiles get.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "relayer.transaction.read",
        tier: CapabilityTier::Execution,
        service: "relayer",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: SIWE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Relayer transaction read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "relayer.transaction.submit",
        tier: CapabilityTier::Execution,
        service: "relayer",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Https,
        auth: SIWE,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: None,
        extension: true,
        summary: "Relayer transaction submit.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "relayer.wallet.deploy",
        tier: CapabilityTier::Execution,
        service: "relayer",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Https,
        auth: SIWE,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: None,
        extension: true,
        summary: "Relayer wallet deploy.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "relayer.wallet.status.read",
        tier: CapabilityTier::Execution,
        service: "relayer",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: SIWE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Relayer wallet status read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "rfq.submit",
        tier: CapabilityTier::Execution,
        service: "rfq",
        operation: CapabilityOperation::Submit,
        transport: CapabilityTransport::Https,
        auth: L2,
        signing: SigningRequirement::Wallet,
        mutates: true,
        cli_command: None,
        extension: true,
        summary: "Rfq submit.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "series.get",
        tier: CapabilityTier::Public,
        service: "series",
        operation: CapabilityOperation::Get,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["series", "get"]),
        extension: false,
        summary: "Series get.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "series.list",
        tier: CapabilityTier::Public,
        service: "series",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["series", "list"]),
        extension: false,
        summary: "Series list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "settlement.readiness.check",
        tier: CapabilityTier::Wallet,
        service: "settlement",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Rpc,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Settlement readiness check.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "settlement.redeem.plan",
        tier: CapabilityTier::Wallet,
        service: "settlement",
        operation: CapabilityOperation::Create,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Settlement redeem plan.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "settlement.redeemables.read",
        tier: CapabilityTier::Public,
        service: "settlement",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Settlement redeemables read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "simulation.book.execute",
        tier: CapabilityTier::Public,
        service: "simulation",
        operation: CapabilityOperation::Simulate,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Simulation book execute.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "sports.list",
        tier: CapabilityTier::Public,
        service: "sports",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["sports", "list"]),
        extension: false,
        summary: "Sports list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "sports.marketTypes.list",
        tier: CapabilityTier::Public,
        service: "sports",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["sports", "market-types"]),
        extension: false,
        summary: "Sports market types list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "sports.teams.list",
        tier: CapabilityTier::Public,
        service: "sports",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["sports", "teams"]),
        extension: false,
        summary: "Sports teams list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "stream.market.subscribe",
        tier: CapabilityTier::Public,
        service: "stream",
        operation: CapabilityOperation::Stream,
        transport: CapabilityTransport::Wss,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Stream market subscribe.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "stream.user.subscribe",
        tier: CapabilityTier::Authenticated,
        service: "stream",
        operation: CapabilityOperation::Stream,
        transport: CapabilityTransport::Wss,
        auth: L2,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Stream user subscribe.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "tags.get",
        tier: CapabilityTier::Public,
        service: "tags",
        operation: CapabilityOperation::Get,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["tags", "get"]),
        extension: false,
        summary: "Tags get.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "tags.list",
        tier: CapabilityTier::Public,
        service: "tags",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["tags", "list"]),
        extension: false,
        summary: "Tags list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "tags.related.list",
        tier: CapabilityTier::Public,
        service: "tags",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["tags", "related"]),
        extension: false,
        summary: "Tags related list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "tags.relatedTags.list",
        tier: CapabilityTier::Public,
        service: "tags",
        operation: CapabilityOperation::List,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["tags", "related-tags"]),
        extension: false,
        summary: "Tags related tags list.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "wallet.address.read",
        tier: CapabilityTier::Wallet,
        service: "wallet",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: Some(&["wallet", "address"]),
        extension: false,
        summary: "Wallet address read.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "wallet.batch.sign",
        tier: CapabilityTier::Wallet,
        service: "wallet",
        operation: CapabilityOperation::Sign,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::Wallet,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Wallet batch sign.",
        status: CapabilityStatus::Planned,
    },
    Capability {
        id: "wallet.deposit.derive",
        tier: CapabilityTier::Wallet,
        service: "wallet",
        operation: CapabilityOperation::Derive,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Wallet deposit derive.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "wallet.proxy.derive",
        tier: CapabilityTier::Wallet,
        service: "wallet",
        operation: CapabilityOperation::Derive,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Wallet proxy derive.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "wallet.readiness.check",
        tier: CapabilityTier::Wallet,
        service: "wallet",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Rpc,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Wallet readiness check.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "wallet.safe.derive",
        tier: CapabilityTier::Wallet,
        service: "wallet",
        operation: CapabilityOperation::Derive,
        transport: CapabilityTransport::Local,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Wallet safe derive.",
        status: CapabilityStatus::Implemented,
    },
    Capability {
        id: "web.cryptoMarkets.read",
        tier: CapabilityTier::Public,
        service: "web",
        operation: CapabilityOperation::Read,
        transport: CapabilityTransport::Https,
        auth: NONE,
        signing: SigningRequirement::None,
        mutates: false,
        cli_command: None,
        extension: true,
        summary: "Web crypto markets read.",
        status: CapabilityStatus::Planned,
    },
];
